In [1]:
import numpy as np

In [58]:
# Define the matrix
A = np.array([[6,  -2, 2,  4],
              [12, -8, 6, 10],
              [ 3, -13, 9, 3],
              [-6, 4, 1, -18]])

In [95]:
# Create a function that finds the U of A
def decompose_LU(matrix, verbose=False):
    shape = matrix.shape
    n = shape[0]
    
    L = np.eye(n, n)
    U = matrix.copy()

    for i in range(1, n):
        for j in range(i):
            L[i, j] = U[i, j]/U[j, j]
            U[i] = U[i] - L[i, j]*U[j]
            
            if verbose == True:
                print("\n\n")
                print("Step", j+1, "of Row", i+1)
                print("_ _ _ _ _ _ _ _ _ _ ", end = "\n\n")
                print("L", L, "U", U, sep="\n\n", end="\n\n\n")
            
    return L, U

In [97]:
L, U = decompose_LU(A)

In [98]:
L

array([[ 1. ,  0. ,  0. ,  0. ],
       [ 2. ,  1. ,  0. ,  0. ],
       [ 0.5,  3. ,  1. ,  0. ],
       [-1. , -0.5,  2. ,  1. ]])

In [102]:
U

array([[ 6, -2,  2,  4],
       [ 0, -4,  2,  2],
       [ 0,  0,  2, -5],
       [ 0,  0,  0, -3]])

In [101]:
np.all(np.matmul(L, U) == A)

True

In [104]:
Q = np.array([[3, -0.1, -0.2], [0.1, 7, -0.3], [0.3, -0.2, 10]])

In [105]:
decompose_LU(Q)

(array([[ 1.        ,  0.        ,  0.        ],
        [ 0.03333333,  1.        ,  0.        ],
        [ 0.1       , -0.02712994,  1.        ]]),
 array([[ 3.        , -0.1       , -0.2       ],
        [ 0.        ,  7.00333333, -0.29333333],
        [ 0.        ,  0.        , 10.01204188]]))

In [106]:
K = np.array([[1, -2, 3], [-1, 3, 1], [2, -5, 5]])

In [107]:
decompose_LU(K)

(array([[ 1.,  0.,  0.],
        [-1.,  1.,  0.],
        [ 2., -1.,  1.]]),
 array([[ 1, -2,  3],
        [ 0,  1,  4],
        [ 0,  0,  3]]))

In [108]:
A = np.array([[-1, 2, -3, 5], [1, 3, 2, -1], [3, -3, 2, 4], [4, 2, 5, 1]])

In [109]:
decompose_LU(A)

(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [-1.        ,  1.        ,  0.        ,  0.        ],
        [-3.        ,  0.6       ,  1.        ,  0.        ],
        [-4.        ,  2.        ,  0.83333333,  1.        ]]),
 array([[-1,  2, -3,  5],
        [ 0,  5, -1,  4],
        [ 0,  0, -6, 16],
        [ 0,  0,  0,  0]]))