In [135]:
import numpy as np

In [136]:
# Define the matrix
A = np.array([[6,  -2, 2,  4],
              [12, -8, 6, 10],
              [ 3, -13, 9, 3],
              [-6, 4, 1, -18]])

In [137]:
# Create a function that finds computes the LU decomposition of "A"
def decompose_LU(matrix, verbose=False):
    shape = matrix.shape
    n = shape[0]
    
    L = np.eye(n, n)
    U = matrix.copy()

    for i in range(1, n):
        for j in range(i):
            L[i, j] = U[i, j]/U[j, j]
            U[i] = U[i] - L[i, j]*U[j]
            
            if verbose == True:
                print("\n\n")
                print("Step", j+1, "of Row", i+1)
                print("_ _ _ _ _ _ _ _ _ _ ", end = "\n\n")
                print("L", L, "U", U, sep="\n\n", end="\n\n\n")
            
    return L, U

In [138]:
L, U = decompose_LU(A)

In [139]:
L

array([[ 1. ,  0. ,  0. ,  0. ],
       [ 2. ,  1. ,  0. ,  0. ],
       [ 0.5,  3. ,  1. ,  0. ],
       [-1. , -0.5,  2. ,  1. ]])

In [140]:
U

array([[ 6, -2,  2,  4],
       [ 0, -4,  2,  2],
       [ 0,  0,  2, -5],
       [ 0,  0,  0, -3]])

In [141]:
np.all(np.matmul(L, U) == A)

True

In [143]:
import sympy as sp

In [144]:
sp.init_session()

IPython console for SymPy 1.5.1 (Python 3.7.6-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/1.5.1/



In [189]:
# Compute Y: LY = B
Y = np.array([x, y, z, t])
B = [16, 26, -19, -34]


for i in range(4):
    M = np.matmul(L, Y)
    eqn = Eq(M[i], B[i])
    Y[i] = solve(eqn, Y[i])[0]

Y.reshape(1, 4)
Y.astype("int")

array([16, -6, -9, -3])

In [197]:
# Compute X: UX = Y
# Compute Y: LY = B
X = np.array([x, y, z, t])

for i in range(3, -1, -1):
    M = np.matmul(U, X)
    eqn = Eq(M[i], Y[i])
    X[i] = solve(eqn, X[i])[0]
    display(eqn)
    print(X)
    print(X[i])

[x y z 1.00000000000000]
1.00000000000000


[x y -2.00000000000000 1.00000000000000]
-2.00000000000000


[x 1.00000000000000 -2.00000000000000 1.00000000000000]
1.00000000000000


[3.00000000000000 1.00000000000000 -2.00000000000000 1.00000000000000]
3.00000000000000


array([3.00000000000000, 1.00000000000000, -2.00000000000000,
       1.00000000000000], dtype=object)

In [167]:
solve?

In [157]:
for i in range(len(M)):
    print(M[i])

1.0*x
2.0*x + 1.0*y
0.5*x + 3.0*y + 1.0*z
1.0*t - 1.0*x - 0.5*y + 2.0*z


In [118]:
eqn = Eq(x+9, 8)

In [124]:
solve(eqn)[0]

In [104]:
Q = np.array([[3, -0.1, -0.2], [0.1, 7, -0.3], [0.3, -0.2, 10]])

In [105]:
decompose_LU(Q)

(array([[ 1.        ,  0.        ,  0.        ],
        [ 0.03333333,  1.        ,  0.        ],
        [ 0.1       , -0.02712994,  1.        ]]),
 array([[ 3.        , -0.1       , -0.2       ],
        [ 0.        ,  7.00333333, -0.29333333],
        [ 0.        ,  0.        , 10.01204188]]))

In [106]:
K = np.array([[1, -2, 3], [-1, 3, 1], [2, -5, 5]])

In [107]:
decompose_LU(K)

(array([[ 1.,  0.,  0.],
        [-1.,  1.,  0.],
        [ 2., -1.,  1.]]),
 array([[ 1, -2,  3],
        [ 0,  1,  4],
        [ 0,  0,  3]]))

In [108]:
A = np.array([[-1, 2, -3, 5], [1, 3, 2, -1], [3, -3, 2, 4], [4, 2, 5, 1]])

In [109]:
decompose_LU(A)

(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [-1.        ,  1.        ,  0.        ,  0.        ],
        [-3.        ,  0.6       ,  1.        ,  0.        ],
        [-4.        ,  2.        ,  0.83333333,  1.        ]]),
 array([[-1,  2, -3,  5],
        [ 0,  5, -1,  4],
        [ 0,  0, -6, 16],
        [ 0,  0,  0,  0]]))