# LU Decomposition 

## Step 1: Import Libraries

In [296]:
import numpy as np
import sympy as sp

### Set up Sympy for use

In [297]:
sp.init_session()

IPython console for SymPy 1.5.1 (Python 3.7.6-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/1.5.1/



## Step 2: Input Question

*Define the coefficient matrix as A and the constant matrix as B*

In [294]:
# Define the matrix
A = np.array([[6,  -2, 2,  4],
              [12, -8, 6, 10],
              [ 3, -13, 9, 3],
              [-6, 4, 1, -18]])

B = [16, 26, -19, -34]

## Step 3: Create a Function to Compute LU Decomposition

In [298]:
# Create a function that finds computes the LU decomposition of "A"
def decompose_LU(matrix, verbose=False):
    shape = matrix.shape
    n = shape[0]
    
    L = np.eye(n, n)
    U = matrix.copy()

    for i in range(1, n):
        for j in range(i):
            L[i, j] = U[i, j]/U[j, j]
            U[i] = U[i] - L[i, j]*U[j]
            
            if verbose == True:
                print("\n\n")
                print("Step", j+1, "of Row", i+1)
                print("_ _ _ _ _ _ _ _ _ _ ", end = "\n\n")
                print("L", L, "U", U, sep="\n\n", end="\n\n\n")
            
    return L, U

In [254]:
L, U = decompose_LU(A)

## Step 4: Create a Function to Compute Y

*Y is defined as the matrix for which LY = B*

In [301]:
def compute_Y(L, B):
    n = L.shape[0]
    list = ["y_" + str(i+1) for i in range(n)]
    Y = np.array(symbols(" ".join(list)))
    
    for i in range(n):
        M = np.matmul(L, Y)
        eqn = Eq(M[i], B[i])
        Y[i] = solve(eqn, Y[i])[0]

    Y.reshape(1, n)
    Y = Y.astype("int") 
    
    return Y

In [302]:
Y = compute_Y(L, B)

## Step 5: Create a Function for Backward Substitution

In [303]:
# Compute X: UX = Y
def compute_X(U, Y):
    n = L.shape[0]
    list = ["x_" + str(i+1) for i in range(n)]
    X = np.array(symbols(" ".join(list)))
    
    for i in range(n-1, -1, -1):
        M = np.matmul(U, X)
        eqn = Eq(M[i], Y[i])
        X[i] = solve(eqn, X[i])[0]
        
    X.reshape(1, n)
    
    
    return X

X = compute_X(U, Y)

In [104]:
Q = np.array([[3, -0.1, -0.2], [0.1, 7, -0.3], [0.3, -0.2, 10]])

In [105]:
decompose_LU(Q)

(array([[ 1.        ,  0.        ,  0.        ],
        [ 0.03333333,  1.        ,  0.        ],
        [ 0.1       , -0.02712994,  1.        ]]),
 array([[ 3.        , -0.1       , -0.2       ],
        [ 0.        ,  7.00333333, -0.29333333],
        [ 0.        ,  0.        , 10.01204188]]))

In [106]:
K = np.array([[1, -2, 3], [-1, 3, 1], [2, -5, 5]])

In [107]:
decompose_LU(K)

(array([[ 1.,  0.,  0.],
        [-1.,  1.,  0.],
        [ 2., -1.,  1.]]),
 array([[ 1, -2,  3],
        [ 0,  1,  4],
        [ 0,  0,  3]]))

In [108]:
A = np.array([[-1, 2, -3, 5], [1, 3, 2, -1], [3, -3, 2, 4], [4, 2, 5, 1]])

In [109]:
decompose_LU(A)

(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [-1.        ,  1.        ,  0.        ,  0.        ],
        [-3.        ,  0.6       ,  1.        ,  0.        ],
        [-4.        ,  2.        ,  0.83333333,  1.        ]]),
 array([[-1,  2, -3,  5],
        [ 0,  5, -1,  4],
        [ 0,  0, -6, 16],
        [ 0,  0,  0,  0]]))